version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/:/app/
      - /app/node_modules
    environment:
      - VUE_APP_BACKEND_URL=http://backend:5000
      - NODE_ENV=development
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app:/app
    environment:
      - FLASK_ENV=development

networks:
  default:
    driver: bridge
